"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { createInjectedClient } from "@/lib/genlayer/client";
import { chain, CHAIN_NAME } from "@/lib/genlayer/config";
import { applyProviderEvent, chainIdHex, DISCONNECTED, hydrateWalletState, MANUAL_DISCONNECT_KEY, nextWalletState, networkLabel, networkVerdict, parseChainId, writeGate, type NetworkVerdict, type WalletState } from "@/lib/wallet-session";

type Value = { address?: `0x${string}`; hasInjected: boolean; connecting: boolean; hydrating: boolean; error?: string; network: NetworkVerdict; networkName: string; canWrite: boolean; writeBlockedReason?: string; connect: () => Promise<void>; switchNetwork: () => Promise<void>; disconnect: () => void; getWriteClient: () => Promise<Awaited<ReturnType<typeof createInjectedClient>>> };
const Ctx = createContext<Value | null>(null);

export function WalletProvider({ children }: { children: React.ReactNode }) {
  const [wallet, setWallet] = useState<WalletState>(DISCONNECTED);
  const [hasInjected, setHasInjected] = useState(false);
  const [connecting, setConnecting] = useState(false);
  const [hydrating, setHydrating] = useState(true);
  useEffect(() => { const p = window.ethereum; if (!p) { queueMicrotask(() => setHydrating(false)); return; } queueMicrotask(() => setHasInjected(true)); const manual = window.localStorage.getItem(MANUAL_DISCONNECT_KEY) === "true"; void p.request({ method: "eth_accounts" }).then(async accounts => { if (!manual) { const chainId = await p.request({ method: "eth_chainId" }); setWallet(hydrateWalletState(accounts, chainId, false)); } queueMicrotask(() => setHydrating(false)); }).catch(() => queueMicrotask(() => setHydrating(false))); }, []);
  useEffect(() => { const p = window.ethereum; if (!p?.on) return; const manual = () => window.localStorage.getItem(MANUAL_DISCONNECT_KEY) === "true"; const a = (...x: unknown[]) => setWallet(s => applyProviderEvent(s, { type: "accounts-changed", accounts: x[0] }, manual())); const c = (...x: unknown[]) => setWallet(s => applyProviderEvent(s, { type: "chain-changed", chainId: x[0] }, manual())); const d = (...x: unknown[]) => { const v = x[0]; const message = v && typeof v === "object" && "message" in v ? String((v as { message: unknown }).message) : undefined; setWallet(s => applyProviderEvent(s, { type: "provider-disconnected", message }, manual())); }; p.on("accountsChanged", a); p.on("chainChanged", c); p.on("disconnect", d); return () => { p.removeListener?.("accountsChanged", a); p.removeListener?.("chainChanged", c); p.removeListener?.("disconnect", d); }; }, []);
  const switchNetwork = useCallback(async () => { if (!window.ethereum) return; try { await window.ethereum.request({ method: "wallet_switchEthereumChain", params: [{ chainId: chainIdHex(chain.id) }] }); const actual = parseChainId(await window.ethereum.request({ method: "eth_chainId" })); setWallet(s => nextWalletState(s, { type: "chain-changed", chainId: actual })); } catch (e) { setWallet(s => ({ ...s, error: `Wallet could not switch to StudioNet: ${e instanceof Error ? e.message : String(e)}` })); } }, []);
  const connect = useCallback(async () => { if (!window.ethereum) { setWallet({ mode: "none", error: "No injected wallet was found in this browser." }); return; } setHasInjected(true); setConnecting(true); try { window.localStorage.removeItem(MANUAL_DISCONNECT_KEY); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as `0x${string}`[]; if (!accounts?.[0]) throw new Error("The wallet returned no account."); const chainId = parseChainId(await window.ethereum.request({ method: "eth_chainId" })); setWallet(nextWalletState(DISCONNECTED, { type: "connected", address: accounts[0], chainId })); } catch (e) { setWallet(s => nextWalletState(s, { type: "connection-refused", message: e instanceof Error ? e.message : String(e) })); } finally { setConnecting(false); } }, []);
  const disconnect = useCallback(() => { window.localStorage.setItem(MANUAL_DISCONNECT_KEY, "true"); setWallet(s => nextWalletState(s, { type: "forget" })); }, []);
  const getWriteClient = useCallback(async () => { const gate = writeGate(wallet, chain.id, CHAIN_NAME); if (!gate.canWrite || !wallet.address) throw new Error(gate.message ?? "Wallet is not ready to write."); return createInjectedClient(wallet.address); }, [wallet]);
  const value = useMemo(() => { const network = networkVerdict(wallet, chain.id); const gate = writeGate(wallet, chain.id, CHAIN_NAME); return { address: wallet.address, hasInjected, connecting, hydrating, error: wallet.error, network, networkName: networkLabel(network, CHAIN_NAME, wallet.chainId), canWrite: gate.canWrite, writeBlockedReason: gate.message, connect, switchNetwork, disconnect, getWriteClient }; }, [wallet, hasInjected, connecting, hydrating, connect, switchNetwork, disconnect, getWriteClient]);
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export function useWallet() { const value = useContext(Ctx); if (!value) throw new Error("useWallet must be used inside WalletProvider"); return value; }
