export type NetworkVerdict = "correct" | "wrong" | "unknown";
export type WalletState = { mode:"none"|"injected"; address?:`0x${string}`; chainId?:number; error?:string };
export const DISCONNECTED:WalletState={mode:"none"};
export const MANUAL_DISCONNECT_KEY="canonmesh.wallet.manualDisconnect";
export function parseChainId(value:unknown):number|undefined { if(typeof value==="number"&&Number.isFinite(value))return value; if(typeof value!=="string")return undefined; const n=value.startsWith("0x")?Number.parseInt(value.slice(2),16):Number.parseInt(value,10); return Number.isFinite(n)?n:undefined; }
export const chainIdHex=(id:number)=>`0x${id.toString(16)}`;
export function networkVerdict(wallet:WalletState,expected:number):NetworkVerdict { if(wallet.mode!=="injected"||wallet.chainId===undefined)return "unknown"; return wallet.chainId===expected?"correct":"wrong"; }
export function networkLabel(verdict:NetworkVerdict,chainName:string,actual?:number){ if(verdict==="correct")return chainName; if(verdict==="wrong")return `Chain ${actual??"unknown"}`; return "Not connected"; }
export function writeGate(wallet:WalletState,expected:number,chainName:string){ if(wallet.mode!=="injected"||!wallet.address)return {canWrite:false,message:"Connect an injected wallet to write."}; if(wallet.chainId!==expected)return {canWrite:false,message:`Switch your wallet to ${chainName} before writing.`}; return {canWrite:true as const,message:undefined}; }
export function nextWalletState(wallet:WalletState,event:{type:"connected";address:`0x${string}`;chainId?:number}|{type:"accounts-changed";accounts:unknown}|{type:"chain-changed";chainId:unknown}|{type:"provider-disconnected";message?:string}|{type:"connection-refused";message:string}|{type:"forget"}):WalletState { if(event.type==="connected")return {mode:"injected",address:event.address,chainId:event.chainId}; if(event.type==="forget")return DISCONNECTED; if(event.type==="connection-refused")return {...wallet,error:event.message}; if(event.type==="provider-disconnected")return {mode:"none",error:event.message}; if(event.type==="chain-changed")return {...wallet,chainId:parseChainId(event.chainId),error:undefined}; if(event.type==="accounts-changed"){const accounts=Array.isArray(event.accounts)?event.accounts:[];const first=accounts[0];if(typeof first!=="string"||!first.startsWith("0x"))return DISCONNECTED;return {...wallet,mode:"injected",address:first as `0x${string}`,error:undefined}} return wallet; }
export function applyProviderEvent(wallet:WalletState,event:Parameters<typeof nextWalletState>[1],manualDisconnect:boolean):WalletState { if(manualDisconnect&&(event.type==="accounts-changed"||event.type==="chain-changed"))return DISCONNECTED; return nextWalletState(wallet,event); }
export function hydrateWalletState(accounts:unknown,chainId:unknown,manualDisconnect:boolean):WalletState { if(manualDisconnect||!Array.isArray(accounts)||typeof accounts[0]!=="string"||!accounts[0].startsWith("0x"))return DISCONNECTED; return nextWalletState(DISCONNECTED,{type:"connected",address:accounts[0] as `0x${string}`,chainId:parseChainId(chainId)}); }
